# Generated by Django 4.1.7 on 2023-06-19 07:28

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capital",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name="city",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name="country",
            name="location",
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
    ]
